# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A6rCtLGyOtHbsDbqbmKbSnnRKfOuk8uA
"""

from sklearn import tree
from sklearn.preprocessing import LabelEncoder
import numpy as np
import pandas as pd
outlook = ['rainy', 'rainy', 'overcast', 'sunny', 'sunny', 'sunny', 'overcast','rainy', 'rainy', 'sunny', 'rainy', 'overcast', 'overcast', 'sunny']
temperature = ['hot', 'hot', 'hot', 'mild', 'cool', 'cool', 'cool', 'mild','cool', 'mild', 'mild', 'mild', 'hot', 'mild']
humidity = ['high', 'high', 'high', 'high', 'normal', 'normal', 'normal','high', 'normal', 'normal', 'normal', 'high', 'normal', 'high']
windy = ['false', 'true', 'false', 'false', 'false', 'true', 'true', 'false','false', 'false', 'true', 'true', 'false', 'true']
label = ['no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no', 'yes','yes', 'yes', 'yes', 'yes', 'no']

df = pd.DataFrame({
    'outlook' : outlook,
    'temperature' : temperature,
    'humidity' : humidity,
    'windy' : windy,
    'label' : label
})


reg = tree.DecisionTreeClassifier()
le  = LabelEncoder()
x = df.drop('label', axis = 1)
y = df['label']
outlook  = le.fit_transform(outlook)
temp = le.fit_transform(temperature)
hum = le.fit_transform(humidity)
win = le.fit_transform(windy)
lab = le.fit_transform(label)
print(lab)
feat = list(zip(outlook, temp, hum, win))


feat = np.asarray(feat)
lab = np.asarray(lab)
print(feat)
print(lab)
reg.fit(feat, lab)
y = reg.predict([[2, 1, 0, 0]])
print(y)
#reg.predict(['sunny', 'cool', 'high', 'false'])